### ISSUE TITLE
Is r-multiverse preferred?

### ISSUE THREAD

**Issue by grantmcdermott** [etiennebacher/tidypolars#112]
Hey @etiennebacher,

I noticed that both `tidypolars` and `r-polars` are available on the new [r-multiverse](https://r-multiverse.r-universe.dev/builds) repo. Is this now the canonical source for installing both packages together? Or, should we just see this as potentially convenient duplication beyond your own r-universe builds? 

Thanks

**Comment by eitsupi** [comment]
I have had some private contact with @shikokuchuo, and I believe r-multiverse is still in the testing phase.
See also pola-rs/r-polars#888.

I see the 150-package limit for R-universe as one of the current issues.

**Comment by eitsupi** [comment]
In fact I would like to see r-multiverse become widely available and not bother with CRAN as I find it quite a pain to use Rust on CRAN, but I don't think it's the right time yet.
(We have the double burden of stagnation of rustc on Debian and Fedora on CRAN)

**Comment by grantmcdermott** [comment]
> Sidenote: I saw your repo on polars + duckdb and I'm wondering if you'll include some tidypolars code since you also present duckplyr.

Yup, just adding it now! I meant to do so earlier, but have been absolutely snowed at work. Thank goodness, I got the bulk of the workshop materials done over the weekend.

Will be giving a shout-out to both of you ;-)

**Comment by grantmcdermott** [comment]
Thanks for the clarification on r-multiverse.
