### ISSUE TITLE
Error when using "lazy = TRUE".

### ISSUE THREAD

**Issue by coforfe** [etiennebacher/tidypolars#20]
Hello,

Thanks for this effort to port "polars" to a more modern syntax with pipes.
I am starting to use your package and I got an error with this:

```r
> large_iris <- data.table::rbindlist(rep(list(iris), 50000))
> large_iris_pl <- as_polars(large_iris, lazy = TRUE)
Error in pl$LazyFrame(.data) : attempt to apply non-function
> 
```

While if I omit `lazy = TRUE" everything runs smoothly:

```r
> large_iris_pl <- as_polars(large_iris)
> 
```

This is my `sessioninfo()`

```r
> sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.4.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Madrid
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.1.2           bench_1.1.3           polars_0.6.0.9000    
[4] data.table_1.14.9     tidypolars_0.0.0.9000

loaded via a namespace (and not attached):
 [1] tidyr_1.3.0       utf8_1.2.3        R6_2.5.1          tidyselect_1.2.0 
 [5] magrittr_2.0.3    glue_1.6.2        tibble_3.2.1      pkgconfig_2.0.3  
 [9] generics_0.1.3    lifecycle_1.0.3   cli_3.6.1         fansi_1.0.4      
[13] vctrs_0.6.3       withr_2.5.0       compiler_4.3.0    purrr_1.0.1      
[17] rstudioapi_0.15.0 tools_4.3.0       pillar_1.9.0      rlang_1.1.1 
```

Thanks again,
Carlos.

**Comment by etiennebacher** [comment]
Hello, thank you for testing `tidypolars`. The error is because `pl$LazyFrame()` (which is used internally) is only available since `polars` 0.7.0 and you have the version 0.6.0.9000.

Could you reinstall `polars` with `install.packages("polars", repos = "https://rpolars.r-universe.dev")`, restart the session, and try again?

**Comment by coforfe** [comment]
Hello Etienne,

Yes, thanks!.
I updated and everything now runs smoothly.
What I noticed is that if `dplyr` is not loaded, `collect()` does not work, it generates an error...

Also, for the sake of comparison, I included `tidytable` (of Mark Fairbanks) in the benchmark  and the comparison in terms of memory allocated are impressive, well also in terms of speed.

```r
# A tibble: 3 × 13
  expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result memory               time       gc      
  <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list> <list>               <list>     <list>  
1 polars        107ms    136ms      7.30    25.7KB     0       10     0      1.37s <NULL> <Rprofmem [25 × 3]>  <bench_tm> <tibble>
2 tidypolars    169ms    204ms      5.02   121.2KB     0       10     0      1.99s <NULL> <Rprofmem [164 × 3]> <bench_tm> <tibble>
3 tidytable     317ms    389ms      2.49   601.8MB     5.97    10    24      4.02s <NULL> <Rprofmem [75 × 3]>  <bench_tm> <tibble>
```
Thanks again for the help!
Carlos.

**Comment by etiennebacher** [comment]
>  What I noticed is that if dplyr is not loaded, collect() does not work, it generates an error...

Yes, I chose to not import `dplyr` automatically in the package to keep the number of dependencies low. You have two options:

* use functions prefixed with `pl_`, like `pl_collect()`. In this case, you don't need to load other packages,
* or use the exact same functions as in `dplyr` (or `tidyr`, etc.). In this case, you need to load `dplyr`

If you already use `dplyr` and friends in your scripts, option 2 is the easiest one.

(FYI, this is explained in the ["Get started" vignette](https://www.tidypolars.etiennebacher.com/articles/tidypolars#you-dont-want-to-use-the-tidyverse) but it's always hard to put myself into the shoes of someone who just discovers the package, so any feedback on the docs is also appreciated ;) )

Thanks!

**Comment by etiennebacher** [comment]
Also, I forgot about this but do not trust the memory results of the benchmark, `bench` cannot capture the memory used by the Rust code under the hood.
