### ISSUE TITLE
Support argument `.by`

### ISSUE THREAD

**Issue by coforfe** [etiennebacher/tidypolars#28]
Hello Etienne,

Now in `dplyr` (taking the idea from `tidytable`) the `group_by()` operations are integrated within `mutate()` or `slice_*()` verbs with a new parameter `.by`. 

Using very extensively `tidytable`, using parameter `.by` makes a cleaner code than using `group_by()` followed by `ungroup()`. How do you see using this same syntax in `tidypolars`?

Thanks!
Carlos.

**Comment by etiennebacher** [comment]
Hello, this should definitely be doable but is not a high priority for me. First, I'd like to find a solution for #10 and finish #27. Once this is done, then implementing a `.by` argument should be quite fast.

**Comment by etiennebacher** [comment]
An additional concern for me is that this function was implemented as "experimental" in [`dplyr` 1.1.0](https://dplyr.tidyverse.org/news/index.html#dplyr-110). Given how frequently the API changes, I'd like to wait for this function to stabilize before implementing it here.

**Comment by eitsupi** [comment]
Hadley mentioned gropup_by as one of his biggest regrets in developing dplyr, so I believe the `by` API will not be deprecated.
<https://news.ycombinator.com/item?id=30067406>

**Comment by etiennebacher** [comment]
Good to know, thanks. I'll implement that when I get some time

**Comment by coforfe** [comment]
Thanks Etienne!

Well, in fact now dplyr has included ".by" thanks to Mark Fairbanks who did that in "tidytable" (dplyr for data.table, and also the author of "tidypolars" for Python). Mark now is also one of the main contributors to "dplyr". My impression is that this way of grouping in the own function is cleaner than doing the "group_by" and then "ungroup".

Thanks again for your time and effort!.
Carlos.

**Comment by etiennebacher** [comment]
``` r
library(dplyr, warn.conflicts = FALSE)
library(tidypolars)
#> Registered S3 method overwritten by 'tidypolars':
#>   method          from  
#>   print.DataFrame polars

iris |>
  as_polars() |> 
  filter(Sepal.Length == max(Sepal.Length), .by = Species)
#> shape: (3, 5)
#> ┌──────────────┬─────────────┬──────────────┬─────────────┬────────────┐
#> │ Sepal.Length ┆ Sepal.Width ┆ Petal.Length ┆ Petal.Width ┆ Species    │
#> │ ---          ┆ ---         ┆ ---          ┆ ---         ┆ ---        │
#> │ f64          ┆ f64         ┆ f64          ┆ f64         ┆ cat        │
#> ╞══════════════╪═════════════╪══════════════╪═════════════╪════════════╡
#> │ 5.8          ┆ 4.0         ┆ 1.2          ┆ 0.2         ┆ setosa     │
#> │ 7.0          ┆ 3.2         ┆ 4.7          ┆ 1.4         ┆ versicolor │
#> │ 7.9          ┆ 3.8         ┆ 6.4          ┆ 2.0         ┆ virginica  │
#> └──────────────┴─────────────┴──────────────┴─────────────┴────────────┘

mtcars |> 
  as_polars() |> 
  summarize(
    m_mpg = mean(mpg),
    sd_mpg = sd(mpg),
    .by = c(cyl, drat)
  )
#> shape: (26, 4)
#> ┌─────┬──────┬───────┬──────────┐
#> │ cyl ┆ drat ┆ m_mpg ┆ sd_mpg   │
#> │ --- ┆ ---  ┆ ---   ┆ ---      │
#> │ f64 ┆ f64  ┆ f64   ┆ f64      │
#> ╞═════╪══════╪═══════╪══════════╡
#> │ 6.0 ┆ 3.9  ┆ 21.0  ┆ 0.0      │
#> │ 4.0 ┆ 3.85 ┆ 22.8  ┆ null     │
#> │ 8.0 ┆ 3.07 ┆ 16.3  ┆ 1.053565 │
#> │ 8.0 ┆ 3.23 ┆ 14.7  ┆ null     │
#> │ …   ┆ …    ┆ …     ┆ …        │
#> │ 6.0 ┆ 3.92 ┆ 18.5  ┆ 0.989949 │
#> │ 4.0 ┆ 4.93 ┆ 30.4  ┆ null     │
#> │ 4.0 ┆ 3.7  ┆ 21.5  ┆ null     │
#> │ 6.0 ┆ 3.62 ┆ 19.7  ┆ null     │
#> └─────┴──────┴───────┴──────────┘
```

**Comment by eitsupi** [comment]
Awesome!
