### ISSUE TITLE
Helpers availability?...

### ISSUE THREAD

**Issue by coforfe** [etiennebacher/tidypolars#29]
Hello Etienne,

Sorry, I have just thought about that... reviewing what I use most frequently in `dplyr` or `tidytable`:

- Regarding the helpers (`starts_with`, `contains`, etc), are they available?
- Also, the verb `across()` or `ifelse()` (that last one is quite common).

Thanks!
Carlos.

**Comment by etiennebacher** [comment]
Yes all the tidy selection (including select helpers) work, there's an example in the readme. 

`across()` and `ifelse()` also work.

**Comment by coforfe** [comment]
Thanks Etienne!.
