### ISSUE TITLE
Apple silicon compatability

### ISSUE THREAD

**Issue by P-Courtney** [etiennebacher/tidypolars#30]
> library(tidypolars)
Error: package or namespace load failed for ‘tidypolars’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/.../Library/R/arm64/4.3/library/polars/libs/polars.so':
  dlopen(...Library/R/arm64/4.3/library/polars/libs/polars.so, 0x0006): tried: '.../Library/R/arm64/4.3/library/polars/libs/polars.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/...Library/R/arm64/4.3/library/polars/libs/polars.so' (no such file), '.../Library/R/arm64/4.3/library/polars/libs/polars.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
In addition: Warning message:
package ‘tidypolars’ was built under R version 4.3.1 
> 

**Ensure that you have the latest versions**

`polars` and `tidypolars` are frequently updated. Please reinstall both and check whether the bug still exists:
```r
### Windows and macOS
install.packages("polars", repos = "https://rpolars.r-universe.dev")
install.packages('tidypolars', repos = c('https://etiennebacher.r-universe.dev', 'https://cloud.r-project.org'))

### Linux
install.packages("polars", repos = "https://rpolars.r-universe.dev/bin/linux/jammy/4.3")
remotes::install_github(
  "etiennebacher/tidypolars", 
  repos = c("https://rpolars.r-universe.dev/bin/linux/jammy/4.3", getOption("repos"))
)
```

**Describe the bug**

**To Reproduce**
Please use the R package [`reprex`](https://reprex.tidyverse.org/) to create a minimal and reproducible example.

**Expected behavior**

**Comment by etiennebacher** [comment]
Can you run  `install.packages("polars", repos = "https://rpolars.r-universe.dev")`, restart the session and tell me if it works?

**Comment by etiennebacher** [comment]
Actually this was discussed here: https://github.com/pola-rs/r-polars/issues/4

I don't think R-universe provides a binary for `arm64` so you might have to build `polars` from source. Follow the instructions in the README of `polars`, specifically in the sections "Build from source" and "System dependencies": https://rpolars.github.io/

In any case, this is an issue with `polars`, not `tidypolars` so I'm closing this, but feel free to open an issue in `polars` repo if the problem persists: https://github.com/pola-rs/r-polars

Thanks

**Comment by sorhawell** [comment]
@etiennebacher @P-Courtney  I have made some progress on cross-compilation you can try it out here https://github.com/pola-rs/r-polars/issues/4
