### ISSUE TITLE
Design questions

### ISSUE THREAD

**Issue by etiennebacher** [etiennebacher/tidypolars#7]
Should I use variants of `tidyverse` functions names (like now with `pl_filter()`) or should I add a method for `polars` class (e.g `filter.DataFrame()`) ?

#### Advantages of custom names

- easy to see if a function comes from `tidypolars`
- avoid namespace collision (polars classes have very standard names that could be used elsewhere, e.g `DataFrame`)

#### Advantages of methods

- no need to change existing tidyverse code, just use a polars class instead of data.frame
- separate method for grouped and ungrouped data

**Comment by etiennebacher** [comment]
I'm not sure what's best here but I think it's a good time to decide something and stick to it before there's too much code to change. I'd be curious to have your opinion @sorhawell @eitsupi @vincentarelbundock 

(since you also develop / contribute to `r-polars` maybe you're interested in this as well but of course you don't have to participate)

**Comment by etiennebacher** [comment]
Never used either but from what I can see `tidytable` masks a bunch of function from `dplyr`, which I'd like to avoid here.

For the first question, my concern is that there are other packages out there that have an object of the class `DataFrame` so using these packages + `tidypolars` woud lead to conflict I think. On the other hand, using dplyr S3 method would mean that we can just replace a tibble by a polars Data/LazyFrame and the code should run

**Comment by eitsupi** [comment]
I think the most difficult part of using dplyr's S3 methods is how to evaluate functions used internally, such as `mutate(foo = func(bar))`.
The arrow package translates quite a few functions and maintains a huge amount of code for this purpose...... (I'm working on a few on that https://github.com/apache/arrow/commits?author=eitsupi)

From that perspective, I think it makes sense to add a prefix like `pl_`.

**Comment by sorhawell** [comment]
In the long run I would aim for the mentioned S3 methods.

I made [PR553](https://github.com/extendr/extendr/pull/553) so now we can name the classes as we like to avoid collisions.  E.g. `Expr` can be called `RExpr` on rust side and `PolarsExpr` on R side.

[r-polars own fork of extendr](https://github.com/rpolars/extendr) has adopted  [PR473](https://github.com/extendr/extendr/pull/473) and will adopt  [PR553](https://github.com/extendr/extendr/pull/553) and  [PR555](https://github.com/extendr/extendr/pull/555)

**Comment by vincentarelbundock** [comment]
I assume Etienne knows it already, but perhaps the `poorman` package would be helpful: https://github.com/nathaneastwood/poorman

**Comment by etiennebacher** [comment]
So in the end I kept both:

* I added S3 methods for all functions so that we can replace a classic dataframe with a Polars DataFrame or LazyFrame in tidyverse workflow and it *should* just work (eventually);
* I kept the functions prefixed with `pl_` (e.g `pl_select()`) because S3 methods won't work if `dplyr` or other tidyverse packages are not loaded.

Just for info I think I also figured out how to deal with expressions in `mutate()`:

``` r
library(tidypolars)
library(dplyr, warn.conflicts = FALSE)
  
starwars |> 
  select(name, mass, species) |> 
  group_by(species) |> 
  mutate(mass_norm = mass / mean(mass, na.rm = TRUE)) |> 
  ungroup()
#> # A tibble: 87 × 4
#>    name                mass species mass_norm
#>    <chr>              <dbl> <chr>       <dbl>
#>  1 Luke Skywalker        77 Human       0.930
#>  2 C-3PO                 75 Droid       1.08 
#>  3 R2-D2                 32 Droid       0.459
#>  4 Darth Vader          136 Human       1.64 
#>  5 Leia Organa           49 Human       0.592
#>  6 Owen Lars            120 Human       1.45 
#>  7 Beru Whitesun lars    75 Human       0.906
#>  8 R5-D4                 32 Droid       0.459
#>  9 Biggs Darklighter     84 Human       1.01 
#> 10 Obi-Wan Kenobi        77 Human       0.930
#> # ℹ 77 more rows

starwars |> 
  as_polars() |> 
  select(name, mass, species) |> 
  group_by(species) |> 
  mutate(mass_norm = mass / mean(mass, na.rm = TRUE)) |> 
  ungroup()
#> Warning: 
#> When the dataset is a Polars DataFrame or LazyFrame, `mean()` only needs one argument. Additional arguments will not be used.
#> shape: (87, 4)
#> ┌────────────────┬───────┬─────────┬───────────┐
#> │ name           ┆ mass  ┆ species ┆ mass_norm │
#> │ ---            ┆ ---   ┆ ---     ┆ ---       │
#> │ str            ┆ f64   ┆ str     ┆ f64       │
#> ╞════════════════╪═══════╪═════════╪═══════════╡
#> │ Luke Skywalker ┆ 77.0  ┆ Human   ┆ 0.930156  │
#> │ C-3PO          ┆ 75.0  ┆ Droid   ┆ 1.075269  │
#> │ R2-D2          ┆ 32.0  ┆ Droid   ┆ 0.458781  │
#> │ Darth Vader    ┆ 136.0 ┆ Human   ┆ 1.642873  │
#> │ …              ┆ …     ┆ …       ┆ …         │
#> │ Poe Dameron    ┆ null  ┆ Human   ┆ null      │
#> │ BB8            ┆ null  ┆ Droid   ┆ null      │
#> │ Captain Phasma ┆ null  ┆ null    ┆ null      │
#> │ Padmé Amidala  ┆ 45.0  ┆ Human   ┆ 0.543598  │
#> └────────────────┴───────┴─────────┴───────────┘
```

<sup>Created on 2023-06-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by eitsupi** [comment]
Awesome!

**Comment by vincentarelbundock** [comment]
yeah, ok, this is very cool.
