### ISSUE TITLE
Delete `as_polars` in favor of `polars::as_polars_df` and `polars::as_polars_lf`

### ISSUE THREAD

**Issue by eitsupi** [etiennebacher/tidypolars#76]
Some related thoughts:

- I don't think overwriting the print method is a good idea, it would be better to add another class, like the arrow package has a separate `arrow_dplyr_query` class for `Table`, etc.
  (If we execute dplyr functions on a Table class object, the class will be converted by `arrow:::as_adq`)
- `polars::pl$enable_string_cache()` should be able to run when the package is loaded.

**Comment by etiennebacher** [comment]
Thanks for the comments, I should indeed deprecate `as_polars()` since I reexport `polars::as_polars_*()` functions (those weren't there when I implemented `as_polars()`)

> `polars::pl$enable_string_cache()` should be able to run when the package is loaded.

Isn't it already the case? Do you have an error when you run this?

**Comment by eitsupi** [comment]
> Isn't it already the case? Do you have an error when you run this?

Oh, sorry. I just read the code below and thought that might be necessary, but I don't actually understand what these things do.
https://github.com/etiennebacher/tidypolars/blob/1838b583d0fa4c157d3ad3b6a99abf18d7c3bf8d/R/as_polars.R#L21-L27

**Comment by etiennebacher** [comment]
I removed it in #79, not a good idea to modify the global state via an argument function

**Comment by etiennebacher** [comment]
I'm not super convinced about overwriting the print method, and it should be a separate issue so I'm closing this
