### ISSUE TITLE
Installing release versions of `polars`

### ISSUE THREAD

**Issue by eitsupi** [etiennebacher/tidypolars#77]
I saw <https://github.com/alejandrohagan/1br>.

Since the polars on <https://github.com/r-universe/etiennebacher> currently change whether SIMD is enabled or not depending on the timing of the download, I think it may be better to fix it to the release version as in <https://github.com/rpolars/rpolars.r-universe.dev/blob/5efe35d0d0cd67f7f38d962bbe35b12a24f99a52/packages.json#L3-L5> to avoid user confusion.

Alternatively, `tidypolars` can be added to <https://github.com/rpolars/rpolars.r-universe.dev>.
In that case, installing from <https://rpolars.r-universe.dev> will select the release version of `polars` and `tidypolars` at the same time.

**Comment by etiennebacher** [comment]
Just to clarify, you mean that in my R-universe I should add `branch: "release"` for `r-polars`, right?

https://github.com/etiennebacher/etiennebacher.r-universe.dev/blob/c07b2519c357b73dc2e4ac2c4235cf9420b03345/packages.json#L6-L9

**Comment by eitsupi** [comment]
Technically it's `"*release"`, but you're right.

**Comment by etiennebacher** [comment]
Thanks for the heads-up, done in https://github.com/etiennebacher/etiennebacher.r-universe.dev/commit/fb16b93551050128baa5e972bf9d2512ef3ed386
