### ISSUE TITLE
`dplyr::collect()` should return data.frame, not RPolarsDataFrame

### ISSUE THREAD

**Issue by eitsupi** [etiennebacher/tidypolars#98]
Please check the behavior of the other dplyr backends.

- `dplyr::collect()` is intended to return data.frame (tibble)
- `dplyr::compute()` is intended to return backends' format

https://dplyr.tidyverse.org/reference/compute.html

So here `collect()` should return data.frame and `compute()` should return RPolarsDataFrame.

You can also set the number of rows to return with an optional argument like dbplyr's collect's `n`, so there is no need to maintain your own function `fetch()`.
https://dbplyr.tidyverse.org/reference/collapse.tbl_sql.html

Also check polarssql behavior.
https://rpolars.github.io/r-polarssql/reference/compute.tbl_polarssql_connection.html

**Comment by etiennebacher** [comment]
Thanks, I agree it should probably be changed for consistency with other R packages. I'm just thinking of how I'm gonna make this apparent in the docs. I made a small demo of polars + tidypolars at work and it was very convenient to use the term "collect" independently of whether I was talking about py-polars, r-polars or tidypolars. Using "collect" for py-polars and r-polars but "compute" for tidypolars will introduce some confusion I think

**Comment by eitsupi** [comment]
> Using "collect" for py-polars and r-polars but "compute" for tidypolars will introduce some confusion I think

I don't know why you just issue "collect", I think things like "select", "where" and "group_by" also work differently in polars and dplyr.

**Comment by etiennebacher** [comment]
This will be implemented in 0.8.0, I implemented a warning redirecting to `compute()`. Small summary of behavior by version:

* 0.6.0 (current): `collect` -> Polars DataFrame, no `compute`
* 0.7.0 (next release): `collect` -> Polars DataFrame but warns that behavior will change, `compute` -> Polars DataFrame
* 0.8.0: `collect` -> data.frame, `compute` -> Polars DataFrame
